# Generated by Django 6.0.4 on 2026-05-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCategorias',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TbUsuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nome', models.CharField(max_length=255)),
                ('usu_email', models.EmailField(max_length=254, unique=True)),
                ('usu_senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TbReceitas',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('rec_nome', models.CharField(max_length=255)),
                ('rec_descricao', models.TextField()),
                ('rec_ingredientes', models.TextField()),
                ('rec_modo_preparo', models.TextField()),
                ('rec_tempo_preparo', models.IntegerField()),
                ('rec_rendimento', models.IntegerField()),
                ('rec_imagem', models.ImageField(upload_to='receitas/receitas_static/imagens/')),
                ('rec_data_criacao', models.DateTimeField(auto_now_add=True)),
                ('rec_data_atualizacao', models.DateTimeField(auto_now=True)),
                ('rec_publicada', models.BooleanField(default=False)),
                ('rec_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.tbcategorias')),
                ('rec_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.tbusuario')),
            ],
        ),
    ]
