# Generated by Django 6.0.4 on 2026-05-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TbCategorias',
            new_name='tb_categorias',
        ),
        migrations.RenameModel(
            old_name='TbReceitas',
            new_name='tb_receitas',
        ),
        migrations.RenameModel(
            old_name='TbUsuario',
            new_name='tb_suario',
        ),
    ]
