# Generated by Django 6.0.4 on 2026-05-18 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_tbcategorias_tb_categorias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_receitas',
            name='rec_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tb_receitas',
            name='rec_imagem',
            field=models.ImageField(upload_to='receitas/imagens/'),
        ),
        migrations.DeleteModel(
            name='tb_suario',
        ),
    ]
